### ISSUE TITLE
Method Request: London Unified Prayer Timetable

### ISSUE THREAD

**Issue by ncodee** [engrbm87/HA-islamic-prayer-times#112]
Salaam,

Please consider adding 'London Unified Prayer Timetable' as a calculation method option in the HA integration. It is used by numerous mosques based in London UK, such as East London Mosque (ELM).

More info: 
https://www.londonprayertimes.com/
https://www.eastlondonmosque.org.uk/prayer-times-and-calendar-explained

API: https://www.londonprayertimes.com/api/

Jazāk Allāhu Khayran

**Comment by engrbm87** [comment]
Hello @ncodee , unfortunately this is a totally different api which would require its own library package. Before looking into this case you tell me if any of the available calculation methods in the current integration gives you the prayers times closest to the actual ones. Would it be possible to get the correct times using the tuning option?

**Comment by ncodee** [comment]
> Hello @ncodee , unfortunately this is a totally different api which would require its own library package. Before looking into this case you tell me if any of the available calculation methods in the current integration gives you the prayers times closest to the actual ones. Would it be possible to get the correct times using the tuning option?

I have tested all other calculation methods and fine tuned the latitude/midnight/school, however there is always a slight offset for each prayer. Unfortunately, this makes a significant difference when it comes to prayer times.

Hope you understand, jzk.

**Comment by engrbm87** [comment]
> > Hello @ncodee , unfortunately this is a totally different api which would require its own library package. Before looking into this case you tell me if any of the available calculation methods in the current integration gives you the prayers times closest to the actual ones. Would it be possible to get the correct times using the tuning option?
> 
> I have tested all other calculation methods and fine tuned the latitude/midnight/school, however there is always a slight offset for each prayer. Unfortunately, this makes a significant difference when it comes to prayer times.
> 
> Hope you understand, jzk.

In addition to choosing the calculation method, school you can offset the times with positive or negative values. Click on the CONFIGURE button and go to the second step of options to set these offsets.
At the moment this is the best option for fine tuning the prayer times.

**Comment by ncodee** [comment]
> > > Hello @ncodee , unfortunately this is a totally different api which would require its own library package. Before looking into this case you tell me if any of the available calculation methods in the current integration gives you the prayers times closest to the actual ones. Would it be possible to get the correct times using the tuning option?
> > 
> > 
> > I have tested all other calculation methods and fine tuned the latitude/midnight/school, however there is always a slight offset for each prayer. Unfortunately, this makes a significant difference when it comes to prayer times.
> > Hope you understand, jzk.
> 
> In addition to choosing the calculation method, school you can offset the times with positive or negative values. Click on the CONFIGURE button and go to the second step of options to set these offsets. At the moment this is the best option for fine tuning the prayer times.

I've clicked on the `CONFIGURE` button, but there is no second step to adjust offsets, it just saves changes. Also, offsets are just a workaround and not really a viable solution, as I will need to adjust the offset every time the calculation method gets updated for each individual prayer time.

**Comment by ncodee** [comment]
Any updates on this please?
